namespace JiraDiscovery.Common.Constants
{
    public static class JobConstants
    {
        public const string AutoGeneratedQuartzJobSuffixValue = "job";

        public const string AutoGeneratedQuartzTriggerSuffixValue = "trigger";
    }
}
